# PetIBM Travis CI.

os: linux
sudo: false
language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - gfortran-6

before_install:
  - export CC="gcc-6"
  - export CXX="g++-6"
  - export FC="gfortran-6"
  - export PETIBM_DIR=$TRAVIS_BUILD_DIR
  - mkdir -p $PETIBM_DIR
  - export PETSC_DIR=$TRAVIS_BUILD_DIR/petsc
  - mkdir -p $PETSC_DIR
  - export PETSC_ARCH=linux-dbg

install:
  - ./scripts/travis-install-petsc.sh $PETSC_DIR $PETSC_ARCH

script:
  - cd $PETIBM_DIR
  - mkdir build
  - cd build
  - $PETIBM_DIR/configure --prefix=$PETIBM_DIR/install CXX=$PETSC_DIR/$PETSC_ARCH/bin/mpicxx CXXFLAGS="-g -O0 -Wno-deprecated -std=c++11" --with-petsc-dir=$PETSC_DIR --with-petsc-arch=$PETSC_ARCH --enable-yamlcpp --enable-gtest
  - make all -j2
  - make check
  - make install

cache:
  directories:
    - petsc

notifications:
  email: false

branches:
  only:
    - master
    - develop
