# PetIBM Travis CI.

os: linux
sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - gfortran-5
      env:
        - _CC=gcc-5
        - _CXX=g++-5
        - _FC=gfortran-5

before_install:
  - sudo apt-get update -qq

install:
  - export PETIBM_DIR=$PWD
  # install PETSc-3.7.4
  - cd ..
  - wget "http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.7.4.tar.gz" -O /tmp/petsc-lite-3.7.4.tar.gz
  - tar xfz /tmp/petsc-lite-3.7.4.tar.gz
  - cd petsc-3.7.4
  - export PETSC_DIR=$PWD
  - export PETSC_ARCH=arch-dbg
  - ./configure --PETSC_ARCH=$PETSC_ARCH --with-cc=$_CC --with-cxx=$_CXX --with-fc=$_FC --COPTFLAGS="-O0" --CXXOPTFLAGS="-O0" --FOPTFLAGS="-O0" --with-debugging=1 --download-fblaslapack --download-mpich
  - make all

script:
  # build PetIBM
  - cd $PETIBM_DIR
  - mkdir build
  - cd build
  - $PETIBM_DIR/configure --prefix=$PWD CXX=$PETSC_DIR/$PETSC_ARCH/bin/mpicxx CXXFLAGS="-g -O0 -std=c++11" --with-petsc-dir=$PETSC_DIR --with-petsc-arch=$PETSC_ARCH
  - make all
  - make check
  - make install

notifications:
  email: false
