# file: .travis.yml
# author: Olivier Mesnard (mesnardo@gwu.edu)
# brief: PetIBM Travis CI.

os: linux

language: cpp

compiler: gcc

before_install:
  - sudo apt-get install gfortran

install:
  - export PETIBM_DIR=$PWD
  # install PETSc-3.5.2
  - cd ..
  - wget "http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.5.2.tar.gz" -O /tmp/petsc-lite-3.5.2.tar.gz
  - tar xfz /tmp/petsc-lite-3.5.2.tar.gz
  - cd petsc-3.5.2
  - export PETSC_DIR=$PWD
  - export PETSC_ARCH=arch-dbg
  - ./configure --PETSC_ARCH=$PETSC_ARCH --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --download-fblaslapack --download-mpich
  - make all

script:
  # build PetIBM
  - cd $PETIBM_DIR
  - mkdir build
  - cd build
  - $PETIBM_DIR/configure --prefix=$PWD CC=$PETSC_DIR/$PETSC_ARCH/bin/mpicc CXX=$PETSC_DIR/$PETSC_ARCH/bin/mpicxx CXXFLAGS="-std=c++0x"
  - make all
  - make check
  - make install

branches:
  only:
    - develop

notifications:
  email: false