# PetIBM Travis CI.

os: linux
sudo: false
language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5

before_install:
  - export CC="gcc-5"
  - export CXX="g++-5"
  - export FC="gfortran-5"
  - export PETIBM_DIR=$PWD
  - $CC --version
  - $CXX --version
  - $FC --version

install:
  # install PETSc-3.7.4
  - cd ..
  - wget "http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.7.4.tar.gz" -O /tmp/petsc-lite-3.7.4.tar.gz
  - tar xfz /tmp/petsc-lite-3.7.4.tar.gz
  - cd petsc-3.7.4
  - export PETSC_DIR=$PWD
  - export PETSC_ARCH=arch-dbg
  - ./configure --PETSC_ARCH=$PETSC_ARCH --with-cc=$CC --with-cxx=$CXX --with-fc=$FC --COPTFLAGS="-O0" --CXXOPTFLAGS="-O0" --FOPTFLAGS="-O0" --with-debugging=1 --download-fblaslapack --download-openmpi
  - make all

script:
  # build PetIBM
  - cd $PETIBM_DIR
  - mkdir build
  - cd build
  - $PETIBM_DIR/configure --prefix=$PWD CXX=$PETSC_DIR/$PETSC_ARCH/bin/mpicxx CXXFLAGS="-g -O0 -std=c++11" --with-petsc-dir=$PETSC_DIR --with-petsc-arch=$PETSC_ARCH
  - make all
  - make check
  - make install

notifications:
  email: false
