flow:
  nu: 0.01
  initialVelocity: [1.0, 0.0, 0.0]
  boundaryConditions:
    - location: xMinus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: xPlus
      u: [CONVECTIVE, 1.0]
      v: [CONVECTIVE, 0.0]
      w: [CONVECTIVE, 0.0]
    - location: yMinus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: yPlus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: zMinus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]
    - location: zPlus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
      w: [DIRICHLET, 0.0]

mesh:
  - direction: x
    start: -4.0
    subDomains:
      - end: -0.5
        cells: 43
        stretchRatio: 0.970026190707
      - end: 0.7
        cells: 30
        stretchRatio: 1.0
      - end: 3.1
        cells: 55
        stretchRatio: 1.0298

  - direction: y
    start: -5.0
    subDomains:
      - end: -0.6
        cells: 13
        stretchRatio: 0.767872226062
      - end: 0.6
        cells: 30
        stretchRatio: 1.0
      - end: 5.0
        cells: 13
        stretchRatio: 1.3023

  - direction: z
    start: -5.0
    subDomains:
      - end: -1.2
        cells: 13
        stretchRatio: 0.769526741054
      - end: 1.2
        cells: 60
        stretchRatio: 1.0
      - end: 5.0
        cells: 13
        stretchRatio: 1.2995

parameters:
  dt: 0.01
  startStep: 0
  nt: 2000
  nsave: 2000
  nrestart: 2000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: GPU
    config: ../configs/velocity_solver.txt
  poissonSolver:
    type: GPU
    config: ../configs/poisson_solver.txt
  forcesSolver:
    type: CPU
    config: ../configs/forces_solver.txt

bodies:
  - type: points
    file: flatplateAoA40.body
